### ISSUE TITLE
Not Compatible with Python 3.7

### ISSUE THREAD

**Issue by runekaagaard** [twidi/mixt#39]
Running `mixt-post-install`, gives the following stacktrace:

```
Traceback (most recent call last):
  File "/home/myname/project/venv/bin/mixt-post-install", line 6, in <module>
    from mixt.scripts.mixt_post_install import main
  File "/home/myname/project/venv/lib/python3.7/site-packages/mixt/__init__.py", line 8, in <module>
    from . import exceptions, html as h  # noqa: F401
  File "/home/myname/project/venv/lib/python3.7/site-packages/mixt/html.py", line 24, in <module>
    from .internal.html import (  # noqa: F401  # pylint: disable=unused-import
  File "/home/myname/project/venv/lib/python3.7/site-packages/mixt/internal/html.py", line 7, in <module>
    from .base import (  # noqa: F401  # isort: skip  # pylint: disable=unused-import
  File "/home/myname/project/venv/lib/python3.7/site-packages/mixt/internal/base.py", line 9, in <module>
    from .proptypes import BasePropTypes
  File "/home/myname/project/venv/lib/python3.7/site-packages/mixt/internal/proptypes.py", line 7, in <module>
    import enforce  # we use "enforce" to check complex types
  File "/home/myname/project/venv/lib/python3.7/site-packages/enforce/__init__.py", line 1, in <module>
    from .decorators import runtime_validation
  File "/home/myname/project/venv/lib/python3.7/site-packages/enforce/decorators.py", line 11, in <module>
    from .enforcers import apply_enforcer, Parameters, GenericProxy
  File "/home/myname/project/venv/lib/python3.7/site-packages/enforce/enforcers.py", line 10, in <module>
    from .validator import init_validator, Validator
  File "/home/myname/project/venv/lib/python3.7/site-packages/enforce/validator.py", line 4, in <module>
    from .parsers import get_parser
  File "/home/myname/project/venv/lib/python3.7/site-packages/enforce/parsers.py", line 225, in <module>
    typing.TupleMeta: _parse_tuple,
AttributeError: module 'typing' has no attribute 'TupleMeta'
```
 See:
- https://github.com/RussBaz/enforce/issues/71
- https://github.com/HPAC/matchpy/issues/36

**Comment by twidi** [comment]
Mixt, as of version 1.2,  now supports python 3.7 and 3.8 in addition to 3.6

Thanks for the report.
